
num1=int(input("введите 1-е число: "))      
num2=int(input("введите 2-е число: "))
num3=int(input("введите 3-е число: "))
print(f"результат суммы:{num1+num2+num3} ")
print(f"результат множения:{num1*num2*num3} ")
print("< 2-я задача >")
print("остаток после выплат")
num5=float(input("введите ведите доход за месяц: "))
num6=float(input("введите банковский платёж: "))
num7=float(input("ведите задолжность комунальных услуг: "))
num8=float(num6+num7)
print(f"остаток после выплат: {num5-num8} ")
print("< 3-я задача >")
print("площадь ромба")
d1=float(input("введите 1-е число: "))      
d2=float(input("введите 2-е число: "))
S=(d1*d2)/2
print(F"площадь ромба равна: {S} ")
print("< 4-я задача >")
print("To be")
print("or not")
print("to be")
print("< 5-я задача >")
print("< цитата 1-я версия >")
print("Life is what happenes")
print("\twhen")
print("\t\tyou'busy making plans")
print("\t\t\t\tJohn Lennon")
print("< цитата 2-я версия >")
print("\n\t")
print("Life is what happenes")
print("\n\twhen")
print("\n\t\tyou'busy making plans")
print("\n\t\t\t\tJohn Lennon")
    
